import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div data-theme="light" className="bg-[url('/background.svg')]">
        <Navbar />
        <div className="bg=[url('/background.svg')]">
          <Hero />
        </div>
      </div>
    </>
  );
}
